name: pre-commit
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y hunspell-ca
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0
      - name: Commit files
        if: failure() && startsWith(github.ref, 'refs/heads')
        run: |
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git checkout -- .github/workflows
            git commit -m "pre-commit" -a
          fi
      - name: Push changes
        if: failure() && startsWith(github.ref, 'refs/heads')
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
